"""
Transcript ORM model for MVRAG AI.

Stores Whisper transcription segments for uploaded videos.
"""

from __future__ import annotations

from sqlalchemy import Float, ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database.base import Base
from src.models.base_model import BaseModel


class Transcript(Base, BaseModel):
    """
    Represents one transcription segment generated by Whisper.
    """

    __tablename__ = "transcripts"

    __table_args__ = (
        Index("idx_transcript_video_id", "video_id"),
        Index("idx_transcript_time", "start_time", "end_time"),
    )

    # ------------------------------------------------------------------
    # Foreign Key
    # ------------------------------------------------------------------

    video_id: Mapped[int] = mapped_column(
        ForeignKey("videos.id", ondelete="CASCADE"),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Transcript Information
    # ------------------------------------------------------------------

    start_time: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    end_time: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    language: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="en",
    )

    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=1.0,
    )

    # ------------------------------------------------------------------
    # Relationship
    # ------------------------------------------------------------------

    video: Mapped["Video"] = relationship(
        back_populates="transcripts",
    )

    def __repr__(self) -> str:
        return (
            f"Transcript("
            f"id={self.id}, "
            f"video_id={self.video_id}, "
            f"start={self.start_time}, "
            f"end={self.end_time})"
        )


from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.models.video import Video